### ISSUE TITLE
Running in docker

### ISSUE THREAD

**Issue by xfgavin** [metrumresearchgroup/gridengine_prometheus#20]
Hi there,

I met another issue using docker.
My sge_root is at /var/lib/gridengine and my sge_cell is fmri.cn
So I wrote my docker-compose.yml as below:
```
version: '2'
services:
  sge-exporter:
    image: gridengine-exporter
    ports:
      - "9081:9081"
    command: "--pidfile /tmp/sge-exporter.pid --sge_root /mnt --sge_cell fmri.cn"
    environment:
      TEST: "true"
    volumes:
      - /var/lib/gridengine:/mnt:ro
```
When I ran and requested metrics, I got error:
sge-exporter_1  | time="2020-05-08T08:17:08Z" level=info msg="Getting ready to start exporter on port 9081"
sge-exporter_1  | time="2020-05-08T08:17:16Z" level=error msg="Couldn't locate binaryexec: \"qstat\": executable file not found in $PATH"
sge-exporter_1  | time="2020-05-08T08:17:16Z" level=error msg="There was an error processing the XML output" error="Couldn't locate the binary"

I then grabbed the compiled binary and tested it manually and it worked.

I wonder if there is something wrong with my yml?
Thank you.

**Comment by shairozan** [comment]
It's not so much something wrong with it, more something missing from it. The exporter expects to find the qstat command in path. Thus when you download the binary it works because the path for your user has been set. One thing I would try doing is setting the PATH variable to include the bin directory of the SGE root. The SGE variables are necessary once the qstat application has been loaded, but you're not even getting to the point of finding it.

**Comment by shairozan** [comment]
```yml
version: '2'
services:
  sge-exporter:
    image: gridengine-exporter
    ports:
      - "9081:9081"
    command: "--pidfile /tmp/sge-exporter.pid --sge_root /mnt --sge_cell fmri.cn"
    environment:
      TEST: "true"
      PATH: /mnt/bin
    volumes:
      - /var/lib/gridengine:/mnt:ro
```

For example, if `/var/lib/gridengine/bin` is where qstat is located.

**Comment by xfgavin** [comment]
Thank you.

Still can't get it up using your dockerfile. I think this is because that the docker image created using your dockerfile doesn't seem to have necessary libs for gridengine client to run.
I did the following and made it work:
1. using your dockerfile I compiled the gridengine_exporter and extracted.
2. I make another docker image using a debian buster slim base image and installed gridengine_client, gridengine_common, musl, and cpp. I also wrapped the gridengine_exporter inside.
```
FROM debian:buster-slim
RUN apt-get update && apt-get -y install gridengine-client musl cpp && apt-get clean && apt-get autoclean && ln -s ld-musl-x86_64.so.1 /lib/libc.musl-x86_64.so.1
COPY ./gridengine_exporter /usr/bin/
```
3. I launched the new image as below:
```
  sge-exporter:
    image: sge_exporter
    command: "/usr/bin/gridengine_exporter --pidfile /tmp/sge-exporter.pid --sge_root /var/lib/gridengine --sge_cell fmri.cn --port 9911"
    volumes:
      - /var/lib/gridengine:/var/lib/gridengine:ro
    network_mode: "host"
```
