### ISSUE TITLE
gridengine_exporter fails on SGE_ARCH

### ISSUE THREAD

**Issue by Gracklewolf** [metrumresearchgroup/gridengine_prometheus#33]
No matter how I set SGE_ARCH, gridengine_exporter fails with message--

gridengine_exporter --sge_arch "lx-amd64" --sge_root "/mnt/software/sge"
Error: failed to validate SGE configuration: the SGE architecture has not been provided

**Comment by bastischubert** [comment]
+1

**Comment by bastischubert** [comment]
using the config file that was in the deb file i was able to get it running (just adjust your setting in the config.yaml accordingly)
however, with only he cmdline params it does not work.

```
#config.yaml 
test: false
port: 9081
pidfile: "/var/run/gridengine_prometheus.pid"
sge:
  arch: "lx-amd64"
  cell: "default"
  execd_port: 6445
  qmaster_port: 6444
  cluster_name: "p6444"
```
